[versions]
compileSdk = "35"
minSdk = "26"
targetSdk = "35"
jvmTarget = "17"
kotlinCompilerExtension = "1.5.13"

kotlin = "1.9.23"
coreKtx = "1.13.1"
gradlePlugin = "8.2.2"
junit = "4.13.2"
lifecycle = "2.8.4"
activityCompose = "1.9.1"
material3 = "1.3.0-rc01"
okhttp = "4.12.0"
composeNavigation = "2.8.0-beta07"
hilt = "2.51"
androidxHiltNavCompose = "1.2.0"
coil = "2.4.0"
recyclerview = "1.3.2"
groupieVersion = "2.9.0"
constraintLayout = "2.1.4"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltNavCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.0" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.3" }
kotlin-serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.11.0" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
squareup-retrofit-converter-kotlin-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version = "2.11.0" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-android-location = { module = "com.google.android.gms:play-services-location", version = "21.3.0" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupieVersion" }
groupie-viewbinding = { module = "com.github.lisawray.groupie:groupie-viewbinding", version.ref = "groupieVersion" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.7.3" }
mockk = { module = "io.mockk:mockk", version = "1.13.12" }


[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
verison-catalog-update-plugin = { id = "nl.littlerobots.version-catalog-update", version = "0.7.0" }
